# Generated by Django 4.1.12 on 2023-10-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActualiteAPP', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actualite',
        ),
    ]
