# Generated by Django 4.1.12 on 2023-10-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActualiteAPP', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='ActualiteDate',
            field=models.DateTimeField(default=1983),
            preserve_default=False,
        ),
    ]
