# Generated by Django 4.1.12 on 2023-10-13 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActualiteAPP', '0004_actualite_actualitedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='ActualiteTag',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='ActualiteDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 16, 5, 35, 508252, tzinfo=datetime.timezone.utc)),
        ),
    ]
