# Generated by Django 4.1.12 on 2023-10-14 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActualiteAPP', '0005_actualite_actualitetag_alter_actualite_actualitedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='ActualiteImage',
            field=models.ImageField(blank=True, upload_to='actualite/'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='ActualiteDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 14, 15, 12, 25, 937721, tzinfo=datetime.timezone.utc)),
        ),
    ]
