# Generated by Django 4.1.12 on 2023-10-14 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActualiteAPP', '0006_actualite_actualiteimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='ActualiteStatus',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='ActualiteDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 14, 19, 22, 3, 68705, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='ActualiteImage',
            field=models.ImageField(blank=True, upload_to='media/actualite/'),
        ),
    ]
