# Generated by Django 4.1.12 on 2023-10-14 19:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ActualiteAPP', '0008_service_alter_actualite_actualitedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='actualite',
            field=models.ForeignKey(blank=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ActualiteAPP.actualite'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actualite',
            name='ActualiteDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 14, 19, 28, 21, 813398, tzinfo=datetime.timezone.utc)),
        ),
    ]
